name: CI
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Check for running processes
        run: |
          pm2 list
          if [ $? -eq 0 ]; then
            pm2 stop all
            pm2 delete all
          else
            echo "No processes running, nothing to stop or delete."
          fi
      - run: npm i
      - run: npm ci
      - run: npm run start
