name: CI
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci

      # ✨ Create .env file from secrets
      - name: Create .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "TOKEN"=${{ secrets.TOKEN }}" >> .env
          echo "SSH_USER"=${{ secrets.SSH_USER }}" >> .env
          echo "SSH_PASS"=${{ secrets.SSH_PASS }}" >> .env

      - run: npm run build
      - run: npm run start
        env:
          NODE_ENV: production
          TOKEN: ${{ secrets.TOKEN }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
